# Generated by Django 2.2.16 on 2022-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220510_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin'), ('superuser', 'superuser')], max_length=20, verbose_name='Права'),
        ),
    ]
