# Generated by Django 2.2.16 on 2022-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='Средний рейтинг'),
            preserve_default=False,
        ),
    ]
